# Generated by Django 4.1.7 on 2023-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_servicios_is_active_alter_servicios_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name_plural': 'Servicios'},
        ),
    ]
