# Generated by Django 4.1.3 on 2023-03-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cliente_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='El mantenimiento de pc de escritorio'),
            preserve_default=False,
        ),
    ]
