# Generated by Django 4.1.7 on 2023-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_servicios_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cliente'),
        ),
    ]
