# Generated by Django 4.1.7 on 2023-03-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cliente_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagencli',
            field=models.ImageField(blank=True, null=True, upload_to='cliente'),
        ),
    ]
